language: node_js
node_js:
- 4.1.2
deploy:
  provider: npm
  email: guten-tag@seiler-gerstmann.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: webdesignberlin/css-reset-and-normalize-sass
